services:
  - type: web
    name: waapi-server
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: WAHA_API_KEY
        value: supercleapi
      - key: WAHA_DASHBOARD_ENABLED
        value: "false"
      - key: WHATSAPP_SWAGGER_ENABLED
        value: "false"
      - key: WAHA_DASHBOARD_NO_PASSWORD
        value: "True"
      - key: WAHA_DASHBOARD_PASSWORD
        value: ""
      - key: WHATSAPP_SWAGGER_NO_PASSWORD
        value: "True"
      - key: WHATSAPP_SWAGGER_PASSWORD
        value: ""
      - key: WHATSAPP_SWAGGER_USERNAME
        value: ""
