services:
  - type: web
    name: waha
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: WHATSAPP_API_KEY
        value: supercleapi
      - key: WAHA_DASHBOARD_ENABLED
        value: "false"
      - key: WAHA_SWAGGER_ENABLED
        value: "false"
      - key: WHATSAPP_HOOK_EVENTS
        value: message,ready,disconnected
      - key: WEBHOOK_URL
        sync: false
